<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { api, wsUrl } from './api'
import GameMap from './components/GameMap.vue'
type User = { id: string; name: string; role: string; team_id: string | null; team_name?: string; game_id?: string }
type Game = { id: string; code: string | null; name: string; status: string }
const user = ref<User | null>(null), adminName = ref('admin'), adminPassword = ref(''), gameCode = ref('RONDE-A'), teamName = ref(''), adminMode = ref(false), error = ref(''), status = ref('')
const objects = ref<any[]>([]), scores = ref<any[]>([]), locations = ref<any[]>([]), tab = ref<'dashboard'|'map'|'score'|'admin'>('dashboard')
const games = ref<Game[]>([]), selectedGameId = ref(''), newGameCode = ref('')
const form = ref({ type: 'PUZZLE', name: '', description: '', latitude: 0, longitude: 0, activation_radius_meters: 40, reward_points: 500, question: '', answer: '', capture_seconds: 60, cooldown_seconds: 300, search_radius_meters: 50 })
let watcher = 0, timer = 0, socket: WebSocket | undefined
const isAdmin = computed(() => user.value?.role === 'ADMIN')
const mascotLogo = 'https://lh3.googleusercontent.com/aida-public/AB6AXuCI316EyPZYN-dEftmLoX_hN9zPIdqM9dqO6-U6-WWOQgjTut0YjabkA1dT_FwdumJG_oEYNpOejgOhkgxRcbvle-A2tlid4vhrRH9FAdE_pCXpn5DRTJRa7bd54zqkxR84nK7F8ST6ll2Ma6SxYXdjAt5AazGe4ubrWSWe3hf0SP0_aoHGefH5-8aOxhKaIXopF4pNJ8EodUvoulgMhsP3DAoTwWAOUcYoquV039ZwmZh0BhXfazGA'
const gameQuery = () => isAdmin.value && selectedGameId.value ? `?game_id=${encodeURIComponent(selectedGameId.value)}` : ''
async function loadGames() { if (!isAdmin.value) return; games.value = await api('/api/admin/games'); if (!selectedGameId.value && games.value[0]) selectedGameId.value = games.value[0].id }
async function load() { await loadGames(); if (isAdmin.value && !selectedGameId.value) { objects.value=[];scores.value=[];locations.value=[];return }; [objects.value, scores.value, locations.value] = await Promise.all([api('/api/game-objects'+gameQuery()), api('/api/scores'+gameQuery()), api('/api/locations'+gameQuery())]) }
async function completeSession(x:any) { localStorage.setItem('cyberjoti-token',x.access_token); user.value=x.user; if(isAdmin.value) await loadGames(); await load(); if(!isAdmin.value) beginGps(); connect() }
async function joinGame() { try { error.value=''; const x = await api('/api/games/join', {method:'POST', body:JSON.stringify({game_code:gameCode.value,team_name:teamName.value})}); await completeSession(x) } catch(e:any) { error.value=e.message } }
async function loginAdmin() { try { error.value=''; const x = await api('/api/auth/login', {method:'POST', body:JSON.stringify({name:adminName.value,password:adminPassword.value})}); await completeSession(x) } catch(e:any) { error.value=e.message } }
function logout() { localStorage.removeItem('cyberjoti-token'); user.value=null; navigator.geolocation?.clearWatch(watcher); clearInterval(timer); socket?.close() }
async function sendLocation(p: GeolocationPosition) { try { await api('/api/location',{method:'POST',body:JSON.stringify({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,timestamp:new Date().toISOString()})}); status.value='GPS online · nauwkeurig tot ' + Math.round(p.coords.accuracy) + 'm'; await load() } catch(e:any){status.value=e.message} }
function beginGps() { if (!navigator.geolocation) { status.value='Deze browser ondersteunt geen GPS.'; return } watcher=navigator.geolocation.watchPosition(sendLocation, e=>status.value='GPS uitgeschakeld: '+e.message, {enableHighAccuracy:true,maximumAge:10000,timeout:15000}); timer=window.setInterval(()=>load().catch(()=>{}),15000) }
function connect() { socket=new WebSocket(wsUrl(isAdmin.value ? selectedGameId.value : user.value?.game_id)); socket.onmessage=()=>load().catch(()=>{}); socket.onclose=()=>setTimeout(()=>user.value&&connect(),3000) }
async function solve(obj:any) { const answer=prompt(obj.name+' — antwoord:'); if (!answer) return; try { const r=await api('/api/puzzles/'+obj.id+'/answer',{method:'POST',body:JSON.stringify({answer})}); alert(r.correct ? 'Correct! +'+r.points:'Niet correct.'); await load() } catch(e:any){alert(e.message)} }
async function capture(obj:any) { try { await api('/api/capture/'+obj.id+'/start',{method:'POST'}); status.value='Capture gestart. Blijf binnen de cirkel; status wordt elke 5 seconden gecontroleerd.'; const t=window.setInterval(async()=>{try{const r=await api('/api/capture/'+obj.id+'/status');if(r.state!=='CAPTURING'){clearInterval(t);status.value='Capture '+r.state.toLowerCase();await load()}}catch(e:any){clearInterval(t);status.value=e.message}},5000) } catch(e:any){alert(e.message)} }
async function scan() { const token=prompt('NFC-token:'); if(!token)return; try{const r=await api('/api/ducks/scan',{method:'POST',body:JSON.stringify({token})});alert(r.name+' gevonden! +'+r.points);await load()}catch(e:any){alert(e.message)} }
function place(coords:{latitude:number;longitude:number}) { form.value.latitude=Number(coords.latitude.toFixed(6)); form.value.longitude=Number(coords.longitude.toFixed(6)); status.value='Punt op kaart gekozen. Vul de details in en sla op.' }
async function addObject() { try { const created=await api('/api/admin/game-objects',{method:'POST',body:JSON.stringify({...form.value,game_id:selectedGameId.value)}); alert(created.scan_token ? 'NFC-token (eenmalig tonen): '+created.scan_token : created.name+' is toegevoegd.'); form.value.name=''; form.value.description=''; form.value.question=''; form.value.answer=''; await load() } catch(e:any){alert(e.message)} }
async function removeObject(obj:any) { if(!confirm('"'+obj.name+'" uitschakelen?'))return; try{await api('/api/admin/game-objects/'+obj.id+'?game_id='+selectedGameId.value,{method:'DELETE'});await load()}catch(e:any){alert(e.message)} }
async function createGame() { try { const game=await api('/api/admin/games',{method:'POST',body:JSON.stringify({game_code:newGameCode.value})}); await loadGames(); selectedGameId.value=game.id; newGameCode.value=''; await load(); connect() } catch(e:any){error.value=e.message} }
async function switchGame() { await load(); connect() }
onMounted(async()=>{if(!localStorage.getItem('cyberjoti-token'))return; try{user.value=await api('/api/auth/me');await load();if(!isAdmin.value) beginGps();connect()}catch{logout()}})
onBeforeUnmount(logout)
</script>
<template>
  <main v-if="!user" class="login"><section class="login-shell"><div class="network-meta"><span><i></i>NET_STATUS: SECURE</span><span><span class="material-symbols-outlined icon-inline">radar</span> NODE: ALLART_HQ</span></div><div class="terminal-hero"><p class="pill">✺ ALLART VAN HEEMSTEDE // JOTI-EDITION</p><div class="crest"><img :src="mascotLogo" alt="CyberJoti eend-mascotte"></div><h1>CYBERJOTI<br>HACK TERMINAL</h1><p>Voer een spelcode en teamnaam in. Geen speleraccount of wachtwoord nodig.</p></div><p class="system-banner">● SYSTEM ONLINE <span>• GPS READY • NFC ACTIVE</span></p><form v-if="!adminMode" class="auth-card" @submit.prevent="joinGame"><div class="section-title"><span><span class="material-symbols-outlined icon-inline">groups</span> TEAM START</span><small>[ CODE // 01 ]</small></div><label>SPELCODE<input v-model="gameCode" required autocomplete="off" /></label><label>TEAMNAAM<input v-model="teamName" required autocomplete="organization" /></label><button><span class="material-symbols-outlined icon-inline">bolt</span> DOE MEE MET SPEL</button><button type="button" class="subtle" @click="adminMode=true">ADMIN LOGIN</button><p v-if="error" class="error">{{ error }}</p></form><form v-else class="auth-card" @submit.prevent="loginAdmin"><div class="section-title"><span><span class="material-symbols-outlined icon-inline">key</span> ADMIN LOGIN</span></div><label>GEBRUIKERSNAAM<input v-model="adminName" autocomplete="username" /></label><label>WACHTWOORD<input v-model="adminPassword" type="password" autocomplete="current-password" /></label><button>INLOGGEN ALS ADMIN</button><button type="button" class="subtle" @click="adminMode=false">TERUG NAAR TEAM START</button><p v-if="error" class="error">{{ error }}</p></form><p class="login-footer">◈ SCOUTING ALLART VAN HEEMSTEDE · PROTOCOL CYBER-2025</p></section></main>
  <main v-else class="app"><header class="hud"><div class="brand"><b class="brand-mark"><img :src="mascotLogo" alt=""></b><b>CYBERJOTI</b></div><div class="user-meta"><span class="online-dot"></span><small>{{ user.name }} · {{ user.role }}</small><button class="subtle" aria-label="Uitloggen" @click="logout"><span class="material-symbols-outlined">logout</span></button></div></header><p class="status">● {{ status || 'GPS INITIALISEREN…' }}</p>
    <section v-if="tab==='dashboard'" class="dashboard"><div class="team-hero"><div class="team-badge"><img :src="mascotLogo" alt=""></div><div><p class="eyebrow">{{ isAdmin ? 'GAME MASTER // LIVE' : 'VELDTEAM // LIVE' }}</p><h1>{{ isAdmin ? 'CONTROL CENTER' : user?.team_name }}</h1><p>{{ isAdmin ? (games.find(g=>g.id===selectedGameId)?.name || 'Kies een spelronde') : 'Scouting Allart' }}</p></div><strong>#{{ scores.findIndex(x => x.team_id === user?.team_id) + 1 || '—' }}</strong></div><div class="stat-grid"><article><small>OBJECTEN</small><b>{{ objects.length }}</b></article><article><small>{{ isAdmin ? 'TEAMS IN RONDE' : 'GPS STATUS' }}</small><b>{{ isAdmin ? locations.length : (locations[0]?.location ? '●' : '—') }}</b></article><article><small>RANG</small><b>#{{ scores.findIndex(x => x.team_id === user?.team_id) + 1 || '—' }}</b></article></div><article v-if="objects[0]" class="mission"><p class="eyebrow"><span class="material-symbols-outlined icon-inline">crisis_alert</span> ACTIEVE MISSIE</p><h2>{{ objects[0].name }}</h2><p>{{ objects[0].description || 'Nieuwe operatie beschikbaar.' }}</p><button @click="tab='map'"><span class="material-symbols-outlined icon-inline">map</span> BEKIJK OP KAART</button></article><button v-if="!isAdmin" class="nfc-quick" @click="scan"><span class="material-symbols-outlined">contactless</span><b>NFC SCANNER STARTEN</b><span class="material-symbols-outlined">arrow_forward</span></button><div class="mission-list"><article v-for="obj in objects" :key="obj.id"><span class="object-icon">{{ obj.type==='PUZZLE'?'◆':obj.type==='CAPTURE_POINT'?'◉':'♧' }}</span><div><small>{{ obj.type.replace('_',' ') }}</small><b>{{ obj.name }}</b></div><button v-if="!isAdmin && obj.type==='PUZZLE'" @click="solve(obj)">OPEN</button><button v-else-if="!isAdmin && obj.type==='CAPTURE_POINT'" @click="capture(obj)">CAPTURE</button><button v-else-if="!isAdmin" @click="scan">SCAN</button></article></div></section>
    <section v-else-if="tab==='map'" class="map-page"><div class="section-head"><div><p class="eyebrow">RADAR // LIVE</p><h1>Veldkaart</h1></div><span class="gps-chip">● GPS LIVE</span></div><div class="filter-row"><span>Alles</span><span>Puzzels</span><span>NFC Eendjes</span><span>Posten</span></div><div class="radar-shell"><GameMap :objects="objects" :locations="locations" /><div class="radar-rings"><i></i><i></i><i></i><b>Jij</b></div></div><div class="map-caption"><b>TACTICAL OVERVIEW</b><span>Eigen positie, teamleden en spelobjecten</span></div></section>
    <section v-else-if="tab==='score'" class="score-page"><p class="eyebrow">LIVE RANKINGS</p><h1>Scoreboard</h1><ol><li v-for="(team, index) in scores" :key="team.team_id"><em>#{{ index + 1 }}</em><i :style="{background:team.color}"></i><span>{{ team.name }}</span><strong>{{ team.score }} PTS</strong></li></ol></section>
    <section v-else-if="isAdmin" class="admin-page"><p class="eyebrow">GAME MASTER // BUILDER</p><h1>Objecten plaatsen</h1><p class="helper">Klik op de kaart om een locatie te kiezen. NFC-tokens worden slechts één keer getoond.</p><GameMap :objects="objects" :locations="locations" editable @place="place"/><form class="builder" @submit.prevent="addObject"><label>TYPE<select v-model="form.type"><option value="PUZZLE">Puzzel</option><option value="CAPTURE_POINT">Capture point</option><option value="PHYSICAL_DUCK">Fysieke eend</option></select></label><label>NAAM<input v-model="form.name" required /></label><label class="wide">BESCHRIJVING<textarea v-model="form.description" /></label><label>LATITUDE<input v-model.number="form.latitude" type="number" step="any" required /></label><label>LONGITUDE<input v-model.number="form.longitude" type="number" step="any" required /></label><label>RADIUS (M)<input v-model.number="form.activation_radius_meters" type="number" min="5" /></label><label>PUNTEN<input v-model.number="form.reward_points" type="number" min="0" /></label><template v-if="form.type==='PUZZLE'"><label class="wide">VRAAG<textarea v-model="form.question" required /></label><label class="wide">ANTWOORD<input v-model="form.answer" required /></label></template><template v-if="form.type==='CAPTURE_POINT'"><label>CAPTURE (SEC)<input v-model.number="form.capture_seconds" type="number" min="5" /></label><label>COOLDOWN (SEC)<input v-model.number="form.cooldown_seconds" type="number" min="0" /></label></template><template v-if="form.type==='PHYSICAL_DUCK'"><label>ZOEKRADIUS (M)<input v-model.number="form.search_radius_meters" type="number" min="5" /></label></template><button>＋ OBJECT TOEVOEGEN</button></form><h2 class="subhead">ACTIEVE OBJECTEN</h2><p v-for="obj in objects" :key="obj.id" class="admin-row"><span>{{ obj.name }}</span><button class="danger" @click="removeObject(obj)">UIT</button></p></section>
    <nav :class="{admin: isAdmin}"><button :class="{active:tab==='dashboard'}" @click="tab='dashboard'"><b>▣</b>Dashboard</button><button :class="{active:tab==='map'}" @click="tab='map'"><b>◎</b>Radar kaart</button><button :class="{active:tab==='score'}" @click="tab='score'"><b>♜</b>Scoreboard</button><button v-if="isAdmin" :class="{active:tab==='admin'}" @click="tab='admin'"><b>⚙</b>Beheer</button></nav></main>
</template>
