import { createApp } from 'vue'
import { createPinia } from 'pinia'
import App from './App.vue'
import './style.css'
import './map-theme.css'
import './prototype-details.css'
import './radar-overrides.css'
import './wide-layout.css'
import './command-board.css'
import './persistent-footer.css'
import './dashboard-stack.css'
import './mobile-field.css'
import './photos.css'
import './round-ui.css'
import './bonus.css'
createApp(App).use(createPinia()).mount('#app')
